//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int member_id { get; set; }
        public string m_name { get; set; }
        public string m_username { get; set; }
        public string m_password { get; set; }
        public Nullable<decimal> m_account { get; set; }
    }
}
